# Day 6: Agenda

- Data Ecosystem
- Numpy
- Pandas intro

### Characteristics of Data

- Volume: Store
- Velocity: process
- Variety: unification

In [1]:
import sys

In [2]:
sys.path

['/Users/ash/cyient/geo',
 '/usr/local/lib/python3.8/site-packages/_pdbpp_path_hack',
 '/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
 '/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
 '/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
 '',
 '/usr/local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/site-packages/IPython/extensions',
 '/Users/ash/.ipython']

In [3]:
sys.getsizeof(4)

28

In [4]:
sys.getsizeof(4.2)

24

In [7]:
sys.getsizeof([])

56

In [8]:
sys.getsizeof({})

64

### Python interpreter implementation

CPython | IronPython(C#) | Jpython (Java)
Python-C API

Programmer
|
code (pandas, matplotlib, sklearn)
|
python (numpy)
|
C (numpy)
|
Machine

In [10]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:
type(arr)

numpy.ndarray

In [15]:
len(arr)

4

In [16]:
sys.getsizeof(arr)

128

In [17]:
sys.getsizeof([1,2,3,4])

88

In [18]:
arr.ndim

1

In [19]:
arr2 = np.array([[1,2],[3,4],[5,6]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(3, 2)

In [28]:
arr = np.arange(10000)

In [29]:
sys.getsizeof(arr)

80096

In [30]:
nums = list(range(10000))
sys.getsizeof(nums)

80056

In [31]:
arr.dtype

dtype('int64')

In [32]:
arr = np.arange(10000, dtype=np.int16)
sys.getsizeof(arr)

20096

In [33]:
[1,2,3,4] + [5,6,7,8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [34]:
# vectorized operations

arr1 = np.arange(10)
arr2 = np.arange(10,20)

arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [35]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
arr2 - arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [38]:
np.arange(4) + np.arange(5)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [39]:
arr1 + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
arr1 * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [41]:
(arr1 + 10) * 5

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [42]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr1.shape

(10,)

In [44]:
arr1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
arr1.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
arr1.reshape((3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [47]:
nums1 = list(range(1000))
nums2 = list(range(1000,2000))

In [48]:
arr1 = np.arange(1000)
arr2 = np.arange(1000,2000)

In [50]:
%%timeit

arr1+arr2;

1.36 µs ± 97.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [52]:
%%timeit

[n1+n2 for n1,n2 in zip(nums1,nums2)];

103 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [54]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr1 >= 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
arr1[0]

0

In [57]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [58]:
arr1[arr1 >= 4]

array([4, 5, 6, 7, 8, 9])

In [59]:
arr1[arr1 < 7]

array([0, 1, 2, 3, 4, 5, 6])

In [60]:
arr1[arr1 != 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr1[(arr1>=2) & (arr1<=7)]

array([2, 3, 4, 5, 6, 7])

In [66]:
arr1[(arr1<2) | (arr1>7)]

array([0, 1, 8, 9])

In [72]:
arr1 = np.random.random(10)
arr2 = np.random.random(10)

In [75]:
# sum of both should be less than 2 and greater than equal to 0
arr1 + arr2 < 2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [77]:
10 - 11
arr1 + 10 # translation

array([10.46038811, 10.74101523, 10.51075091, 10.48943506, 10.02343996,
       10.54728489, 10.20816782, 10.11161117, 10.13463965, 10.66189115])

In [79]:
# arr1 + np.arange(10)
# 0 - 10
arr1 * 10  # scaling

array([4.60388109, 7.41015233, 5.10750907, 4.89435057, 0.23439961,
       5.47284891, 2.08167822, 1.11611168, 1.34639646, 6.61891147])

In [86]:
# 10 - 20
arr1 * 10 + 10

array([14.60388109, 17.41015233, 15.10750907, 14.89435057, 10.23439961,
       15.47284891, 12.08167822, 11.11611168, 11.34639646, 16.61891147])

In [87]:
# 100 - 101
arr1 + 10 * 10

array([100.46038811, 100.74101523, 100.51075091, 100.48943506,
       100.02343996, 100.54728489, 100.20816782, 100.11161117,
       100.13463965, 100.66189115])

In [88]:
# 100 - 110
(arr1 + 10) * 10

array([104.60388109, 107.41015233, 105.10750907, 104.89435057,
       100.23439961, 105.47284891, 102.08167822, 101.11611168,
       101.34639646, 106.61891147])

In [84]:
np.random.randint(10,100)

80

In [92]:
# 90 - 100
(arr1 + 10) * 10 - 10
(arr1 + 10 - 1) * 10
(arr1 + 9) * 10
arr1 * 10 + 90

array([94.60388109, 97.41015233, 95.10750907, 94.89435057, 90.23439961,
       95.47284891, 92.08167822, 91.11611168, 91.34639646, 96.61891147])

In [93]:
arr1

array([0.46038811, 0.74101523, 0.51075091, 0.48943506, 0.02343996,
       0.54728489, 0.20816782, 0.11161117, 0.13463965, 0.66189115])

In [97]:
arr1[arr1>0.5]

array([0.74101523, 0.51075091, 0.54728489, 0.66189115])

In [99]:
# <.25, >.75
arr1[(arr1<.25) | (arr1>.75)]

array([0.02343996, 0.20816782, 0.11161117, 0.13463965])

In [100]:
arr1

array([0.46038811, 0.74101523, 0.51075091, 0.48943506, 0.02343996,
       0.54728489, 0.20816782, 0.11161117, 0.13463965, 0.66189115])

In [101]:
arr2

array([0.12123812, 0.90188818, 0.49364292, 0.71952715, 0.09964094,
       0.20810696, 0.81520818, 0.67241248, 0.32823652, 0.82000311])

In [103]:
# all values in arr1 that are > corresponding values in arr2
arr1[arr1 > arr2]


array([0.46038811, 0.51075091, 0.54728489])

In [104]:
arr2[arr1 > arr2]

array([0.12123812, 0.49364292, 0.20810696])

In [105]:
import pandas as pd

In [107]:
tips = pd.read_csv('data/tips.csv')
tips

total_bill   tip     sex smoker   day    time  size  fraction
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

In [108]:
type(tips)

pandas.core.frame.DataFrame

In [109]:
tips.shape

(244, 8)

In [110]:
len(tips)

244

In [111]:
tips['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [112]:
type(tips['total_bill'])

pandas.core.series.Series

In [113]:
# attribute access syntax
tips.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [114]:
tips

total_bill   tip     sex smoker   day    time  size  fraction
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

In [115]:
tips.head(10)

total_bill   tip     sex smoker  day    time  size  fraction
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808
5       25.29  4.71    Male     No  Sun  Dinner     4  0.186240
6        8.77  2.00    Male     No  Sun  Dinner     2  0.228050
7       26.88  3.12    Male     No  Sun  Dinner     4  0.116071
8       15.04  1.96    Male     No  Sun  Dinner     2  0.130319
9       14.78  3.23    Male     No  Sun  Dinner     2  0.218539

In [116]:
tips.tail(1)

total_bill  tip     sex smoker   day    time  size  fraction
243       18.78  3.0  Female     No  Thur  Dinner     2  0.159744

In [117]:
tips.sample(5)

total_bill   tip     sex smoker   day    time  size  fraction
37        16.93  3.07  Female     No   Sat  Dinner     3  0.181335
143       27.05  5.00  Female     No  Thur   Lunch     6  0.184843
137       14.15  2.00  Female     No  Thur   Lunch     2  0.141343
201       12.74  2.01  Female    Yes  Thur   Lunch     2  0.157771
130       19.08  1.50    Male     No  Thur   Lunch     2  0.078616

In [121]:
tips.tip + 10

0      11.01
1      11.66
2      13.50
3      13.31
4      13.61
       ...  
239    15.92
240    12.00
241    12.00
242    11.75
243    13.00
Name: tip, Length: 244, dtype: float64

In [123]:
tips.tip[tips.tip > 2]

2      3.50
3      3.31
4      3.61
5      4.71
7      3.12
       ... 
232    3.39
234    3.00
238    4.67
239    5.92
243    3.00
Name: tip, Length: 166, dtype: float64

In [124]:
tips[tips.tip > 2]

total_bill   tip     sex smoker   day    time  size  fraction
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
5         25.29  4.71    Male     No   Sun  Dinner     4  0.186240
7         26.88  3.12    Male     No   Sun  Dinner     4  0.116071
..          ...   ...     ...    ...   ...     ...   ...       ...
232       11.61  3.39    Male     No   Sat  Dinner     2  0.291990
234       15.53  3.00    Male    Yes   Sat  Dinner     2  0.193175
238       35.83  4.67  Female     No   Sat  Dinner     3  0.130338
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[166 rows x 8 columns]

In [127]:
len(tips[(tips.tip > 2) & (tips.total_bill > 30)])

29

In [130]:
len(tips[(tips.sex == 'Female') & (tips.time == 'Dinner')])

52

In [132]:
female = tips.sex == 'Female'
dinner = tips.time == 'Dinner'
tipgt2 = tips.tip > 2
tbgt30 = tips.total_bill > 30

In [133]:
len(tips[female & dinner & tipgt2 & tbgt30])

5

In [135]:
tips.sort_values('tip', ascending=False)

total_bill    tip     sex smoker   day    time  size  fraction
170       50.81  10.00    Male    Yes   Sat  Dinner     3  0.196812
212       48.33   9.00    Male     No   Sat  Dinner     4  0.186220
23        39.42   7.58    Male     No   Sat  Dinner     4  0.192288
59        48.27   6.73    Male     No   Sat  Dinner     4  0.139424
141       34.30   6.70    Male     No  Thur   Lunch     6  0.195335
..          ...    ...     ...    ...   ...     ...   ...       ...
0         16.99   1.01  Female     No   Sun  Dinner     2  0.059447
236       12.60   1.00    Male    Yes   Sat  Dinner     2  0.079365
111        7.25   1.00  Female     No   Sat  Dinner     1  0.137931
67         3.07   1.00  Female    Yes   Sat  Dinner     1  0.325733
92         5.75   1.00  Female    Yes   Fri  Dinner     2  0.173913

[244 rows x 8 columns]

In [136]:
tips.sort_values('tip', ascending=False).head(1)

total_bill   tip   sex smoker  day    time  size  fraction
170       50.81  10.0  Male    Yes  Sat  Dinner     3  0.196812

In [138]:
tips.tip.max()

10.0

In [139]:
tips.total_bill.max()

50.81

In [140]:
tips.nlargest(1, 'tip')

total_bill   tip   sex smoker  day    time  size  fraction
170       50.81  10.0  Male    Yes  Sat  Dinner     3  0.196812

In [141]:
tips.nsmallest(1, 'total_bill')

total_bill  tip     sex smoker  day    time  size  fraction
67        3.07  1.0  Female    Yes  Sat  Dinner     1  0.325733

In [142]:
tips.sort_values('total_bill').head(1)

total_bill  tip     sex smoker  day    time  size  fraction
67        3.07  1.0  Female    Yes  Sat  Dinner     1  0.325733

In [143]:
tips.total_bill.min()

3.07

In [144]:
gm = pd.read_csv('data/gapminder_tidy.csv')
gm

Country  Year  fertility    life  population  child_mortality  \
0      Afghanistan  1964      7.671  33.639  10474903.0            339.7   
1      Afghanistan  1965      7.671  34.152  10697983.0            334.1   
2      Afghanistan  1966      7.671  34.662  10927724.0            328.7   
3      Afghanistan  1967      7.671  35.170  11163656.0            323.3   
4      Afghanistan  1968      7.671  35.674  11411022.0            318.1   
...            ...   ...        ...     ...         ...              ...   
10106        Åland  2002        NaN  81.800     26257.0              NaN   
10107        Åland  2003        NaN  80.630     26347.0              NaN   
10108        Åland  2004        NaN  79.880     26530.0              NaN   
10109        Åland  2005        NaN  80.000     26766.0              NaN   
10110        Åland  2006        NaN  80.100     26923.0              NaN   

          gdp                 region  
0      1182.0             South Asia  
1      1182.0             South Asia  
2      1168.0             South Asia  
3      1173.0             South Asia  
4      1187.0             South Asia  
...       ...                    ...  
10106     NaN  Europe & Central Asia  
10107     NaN  Europe & Central Asia  
10108     NaN  Europe & Central Asia  
10109     NaN  Europe & Central Asia  
10110     NaN  Europe & Central Asia  

[10111 rows x 8 columns]